GET http://localhost:5000/users

###
GET http://localhost:5000/users/62799d6fb3e0fc445a78c094

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Testenildo",
    "email": "testenildo@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:5000/users/6279bedcbd13e61c75e66a0e
Content-Type: application/json

{
    "name": "Testenilda",
    "email": "testenilda@gmail.com",
    "gender": "Female"
}

###
DELETE http://localhost:5000/users/6279bedcbd13e61c75e66a0e